name: Build & Test CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: "--privileged --cap-add SYS_ADMIN --device /dev/fuse"
    env:
      TZ: America/New_York
      DEBIAN_FRONTEND: noninteractive
      CC: gcc-10
      CXX: g++-10
    steps:
      - uses: actions/checkout@v1
      - name: install deps
        run: apt update && apt install -yq software-properties-common && add-apt-repository ppa:ubuntu-toolchain-r/ppa && apt update && apt install -yq cmake python3 gcc-10 g++-10 libfuse3-dev fuse3 pkg-config
      - name: configure & build & test & everything
        run: ./script.sh
