name: Build & Test CI

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    options: "--privileged --cap-add SYS_ADMIN --device /dev/fuse"
    steps:
      - uses: actions/checkout@v1
      - name: configure & build & test & everything
        run: ./script.sh
